# Generated by Django 4.0.4 on 2022-07-18 06:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('topikstore', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=250, verbose_name='City')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Surname')),
                ('number', models.CharField(max_length=12, verbose_name='Number')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('post', models.CharField(choices=[('Nova Poshta', 'Нова пошта'), ('Ukrposhta', 'Укрпошта'), ('Justin', 'Justin'), ('Meets', 'Meets')], max_length=150, verbose_name='Post')),
                ('number_of_post', models.CharField(max_length=15, verbose_name="Post's")),
                ('data_create', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('data_update', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('paid', models.BooleanField(default=False, verbose_name='Paid')),
                ('status', models.CharField(choices=[('New', 'New'), ('In prosessing', 'In prosessing'), ('Awaiting delivery', 'Awaiting delivery'), ('Received', 'Received')], max_length=250, verbose_name='Status')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orders.cities', verbose_name='City')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Customer')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='topikstore.products')),
            ],
        ),
    ]
