# Generated by Django 4.0.4 on 2022-07-24 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_cities_options_cities_is_public_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='call',
            field=models.BooleanField(default=True, verbose_name='Call me'),
        ),
        migrations.AlterField(
            model_name='order',
            name='first_name',
            field=models.CharField(max_length=50, verbose_name='Customer name'),
        ),
        migrations.AlterField(
            model_name='order',
            name='number_of_post',
            field=models.CharField(max_length=15, verbose_name='Post number'),
        ),
    ]
