# Generated by Django 4.0.4 on 2022-07-20 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topikstore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='category_en',
            field=models.CharField(max_length=250, null=True, verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='categories',
            name='category_ru',
            field=models.CharField(max_length=250, null=True, verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='categories',
            name='category_uk',
            field=models.CharField(max_length=250, null=True, verbose_name='Category'),
        ),
    ]
