# Generated by Django 4.0.4 on 2022-07-21 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topikstore', '0002_categories_category_en_categories_category_ru_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categories',
            name='category_en',
        ),
        migrations.AddField(
            model_name='subcategories',
            name='subcategory_ru',
            field=models.CharField(max_length=250, null=True, verbose_name='Subcategory'),
        ),
        migrations.AddField(
            model_name='subcategories',
            name='subcategory_uk',
            field=models.CharField(max_length=250, null=True, verbose_name='Subcategory'),
        ),
    ]
