# Generated by Django 4.0.4 on 2022-07-21 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topikstore', '0003_remove_categories_category_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdetail',
            name='contraindications_ru',
            field=models.CharField(max_length=300, null=True, verbose_name='Contraindications'),
        ),
        migrations.AddField(
            model_name='productdetail',
            name='contraindications_uk',
            field=models.CharField(max_length=300, null=True, verbose_name='Contraindications'),
        ),
        migrations.AddField(
            model_name='productdetail',
            name='expiration_date_ru',
            field=models.CharField(max_length=300, null=True, verbose_name='Expiration date'),
        ),
        migrations.AddField(
            model_name='productdetail',
            name='expiration_date_uk',
            field=models.CharField(max_length=300, null=True, verbose_name='Expiration date'),
        ),
        migrations.AddField(
            model_name='productdetail',
            name='storage_conditions_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Storage conditions'),
        ),
        migrations.AddField(
            model_name='productdetail',
            name='storage_conditions_uk',
            field=models.TextField(blank=True, null=True, verbose_name='Storage conditions'),
        ),
        migrations.AddField(
            model_name='productdetail',
            name='terms_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Terms of use'),
        ),
        migrations.AddField(
            model_name='productdetail',
            name='terms_uk',
            field=models.TextField(blank=True, null=True, verbose_name='Terms of use'),
        ),
        migrations.AddField(
            model_name='products',
            name='full_description_ru',
            field=models.TextField(null=True, verbose_name='Full description'),
        ),
        migrations.AddField(
            model_name='products',
            name='full_description_uk',
            field=models.TextField(null=True, verbose_name='Full description'),
        ),
        migrations.AddField(
            model_name='products',
            name='product_ru',
            field=models.CharField(max_length=250, null=True, verbose_name='Product'),
        ),
        migrations.AddField(
            model_name='products',
            name='product_uk',
            field=models.CharField(max_length=250, null=True, verbose_name='Product'),
        ),
        migrations.AddField(
            model_name='products',
            name='short_description_ru',
            field=models.TextField(null=True, verbose_name='Short description'),
        ),
        migrations.AddField(
            model_name='products',
            name='short_description_uk',
            field=models.TextField(null=True, verbose_name='Short description'),
        ),
    ]
